/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.purplecobras.keyboardwarrior.gui.v2;

import javax.swing.ImageIcon;


/**
 *
 * @author JoshPoe
 */
public class ShortcutFrame extends javax.swing.JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form ShortcutFrame
     */
    public ShortcutFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Master_MainPannel = new javax.swing.JPanel();
        Master_LabelPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        MasterPanelLabel = new javax.swing.JLabel();
        Master_SidePanel = new javax.swing.JPanel();
        Logo_Label = new javax.swing.JLabel();
        Layout_Label = new javax.swing.JLabel();
        Shortcut_Label = new javax.swing.JLabel();
        Share_Label = new javax.swing.JLabel();
        Groups_Label = new javax.swing.JLabel();
        Statistics_Label = new javax.swing.JLabel();
        General_Label = new javax.swing.JLabel();
        Help_Label = new javax.swing.JLabel();
        Profile_Label = new javax.swing.JLabel();
        DisplayTextPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SC_JTextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        SC_Key_JList = new javax.swing.JList<>();
        InputTextPanel = new javax.swing.JPanel();
        SC_Descript_JLabel = new javax.swing.JLabel();
        SC_Descript_JTextField = new javax.swing.JTextField();
        SC_Value_JTextField = new javax.swing.JTextField();
        SC_Key_JTextField = new javax.swing.JTextField();
        SC_Key_Label = new javax.swing.JLabel();
        SC_Value_JLabel = new javax.swing.JLabel();
        ButtonPanel = new javax.swing.JPanel();
        Add_button = new java.awt.Button();
        Delete_button = new java.awt.Button();
        Edit_button = new java.awt.Button();
        Save_button = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Master_MainPannel.setBackground(new java.awt.Color(102, 102, 102));
        Master_MainPannel.setPreferredSize(new java.awt.Dimension(650, 550));

        Master_LabelPanel.setBackground(new java.awt.Color(102, 102, 102));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        MasterPanelLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MasterPanelLabel.setForeground(new java.awt.Color(255, 255, 255));
        MasterPanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MasterPanelLabel.setText("Shortcut Manager");
        MasterPanelLabel.setToolTipText("");

        javax.swing.GroupLayout Master_LabelPanelLayout = new javax.swing.GroupLayout(Master_LabelPanel);
        Master_LabelPanel.setLayout(Master_LabelPanelLayout);
        Master_LabelPanelLayout.setHorizontalGroup(Master_LabelPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Master_LabelPanelLayout.createSequentialGroup().addContainerGap()
                        .addGroup(Master_LabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(MasterPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 380,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 380,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap()));
        Master_LabelPanelLayout
                .setVerticalGroup(Master_LabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Master_LabelPanelLayout.createSequentialGroup().addContainerGap()
                                .addComponent(MasterPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        Master_SidePanel.setBackground(new java.awt.Color(51, 51, 51));
        Master_SidePanel.setPreferredSize(new java.awt.Dimension(200, 550));

        Logo_Label.setBackground(new java.awt.Color(11, 11, 11));
        Logo_Label.setForeground(new java.awt.Color(255, 255, 255));
        Logo_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo_Label.setIcon(new ImageIcon("src/com/purplecobras/keyboardwarrior/ico/WHITE_W_HELMET.png")); // NOI18N

        Layout_Label.setBackground(new java.awt.Color(11, 11, 11));
        Layout_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Layout_Label.setForeground(new java.awt.Color(255, 255, 255));
        Layout_Label.setIcon(new ImageIcon("src/com/purplecobras/keyboardwarrior/ico/006-interface.png")); // NOI18N
        Layout_Label.setText("Layout");
        Layout_Label.setPreferredSize(new java.awt.Dimension(70, 50));
        Layout_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Layout_LabelMouseEntered(evt);
            }
        });

        Shortcut_Label.setBackground(new java.awt.Color(11, 11, 11));
        Shortcut_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Shortcut_Label.setForeground(new java.awt.Color(255, 255, 255));
        Shortcut_Label.setIcon(new ImageIcon("src/com/purplecobras/keyboardwarrior/ico/computer_1.png")); // NOI18N
        Shortcut_Label.setText("Shortcuts");
        Shortcut_Label.setPreferredSize(new java.awt.Dimension(70, 50));
        Shortcut_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Shortcut_LabelMouseEntered(evt);
            }
        });

        Share_Label.setBackground(new java.awt.Color(11, 11, 11));
        Share_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Share_Label.setForeground(new java.awt.Color(255, 255, 255));
        Share_Label.setIcon(new ImageIcon("src/com/purplecobras/keyboardwarrior/ico/share.png")); // NOI18N
        Share_Label.setText("Share");
        Share_Label.setPreferredSize(new java.awt.Dimension(70, 50));
        Share_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Share_LabelMouseEntered(evt);
            }
        });

        Groups_Label.setBackground(new java.awt.Color(11, 11, 11));
        Groups_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Groups_Label.setForeground(new java.awt.Color(255, 255, 255));
        Groups_Label.setIcon(new ImageIcon("src/com/purplecobras/keyboardwarrior/ico/networking.png")); // NOI18N
        Groups_Label.setText("Groups");
        Groups_Label.setPreferredSize(new java.awt.Dimension(70, 50));
        Groups_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Groups_LabelMouseEntered(evt);
            }
        });

        Statistics_Label.setBackground(new java.awt.Color(11, 11, 11));
        Statistics_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Statistics_Label.setForeground(new java.awt.Color(255, 255, 255));
        Statistics_Label.setIcon(new ImageIcon("src/com/purplecobras/keyboardwarrior/ico/analytics.png")); // NOI18N
        Statistics_Label.setText("Statistics");
        Statistics_Label.setPreferredSize(new java.awt.Dimension(70, 50));
        Statistics_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Statistics_LabelMouseEntered(evt);
            }
        });

        General_Label.setBackground(new java.awt.Color(11, 11, 11));
        General_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        General_Label.setForeground(new java.awt.Color(255, 255, 255));
        General_Label.setIcon(new ImageIcon("src/com/purplecobras/keyboardwarrior/ico/010-configuration.png")); // NOI18N
        General_Label.setText("General");
        General_Label.setPreferredSize(new java.awt.Dimension(70, 50));
        General_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                General_LabelMouseEntered(evt);
            }
        });

        Help_Label.setBackground(new java.awt.Color(11, 11, 11));
        Help_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Help_Label.setForeground(new java.awt.Color(255, 255, 255));
        Help_Label.setIcon(new ImageIcon("src/com/purplecobras/keyboardwarrior/ico/communication.png")); // NOI18N
        Help_Label.setText("Help");
        Help_Label.setPreferredSize(new java.awt.Dimension(70, 50));
        Help_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Help_LabelMouseEntered(evt);
            }
        });

        Profile_Label.setBackground(new java.awt.Color(11, 11, 11));
        Profile_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Profile_Label.setForeground(new java.awt.Color(255, 255, 255));
        Profile_Label.setIcon(new ImageIcon("src/com/purplecobras/keyboardwarrior/ico/user.png")); // NOI18N
        Profile_Label.setText("Profile");
        Profile_Label.setPreferredSize(new java.awt.Dimension(70, 50));
        Profile_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Profile_LabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout Master_SidePanelLayout = new javax.swing.GroupLayout(Master_SidePanel);
        Master_SidePanel.setLayout(Master_SidePanelLayout);
        Master_SidePanelLayout.setHorizontalGroup(Master_SidePanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Master_SidePanelLayout.createSequentialGroup().addGroup(Master_SidePanelLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Logo_Label, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                Master_SidePanelLayout.createSequentialGroup().addGap(10, 10, 10)
                                        .addGroup(Master_SidePanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Layout_Label, javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Shortcut_Label, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(Master_SidePanelLayout.createSequentialGroup().addContainerGap()
                                .addGroup(Master_SidePanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Groups_Label, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Share_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Statistics_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(General_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Help_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(Profile_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)));

        Master_SidePanelLayout.setVerticalGroup(Master_SidePanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Master_SidePanelLayout.createSequentialGroup()
                        .addComponent(Logo_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Layout_Label, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Shortcut_Label, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Groups_Label, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Share_Label, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Statistics_Label, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(General_Label, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Help_Label, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(Profile_Label, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap()));

        DisplayTextPanel.setBackground(new java.awt.Color(102, 102, 102));

        SC_JTextArea.setBackground(new java.awt.Color(240, 240, 240));
        SC_JTextArea.setColumns(20);
        SC_JTextArea.setRows(5);
        jScrollPane2.setViewportView(SC_JTextArea);

        SC_Key_JList.setBackground(new java.awt.Color(240, 240, 240));
        jScrollPane1.setViewportView(SC_Key_JList);

        javax.swing.GroupLayout DisplayTextPanelLayout = new javax.swing.GroupLayout(DisplayTextPanel);
        DisplayTextPanel.setLayout(DisplayTextPanelLayout);
        DisplayTextPanelLayout.setHorizontalGroup(
                DisplayTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DisplayTextPanelLayout.createSequentialGroup().addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2).addContainerGap()));
        DisplayTextPanelLayout
                .setVerticalGroup(DisplayTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1).addComponent(jScrollPane2));

        InputTextPanel.setBackground(new java.awt.Color(102, 102, 102));

        SC_Descript_JLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SC_Descript_JLabel.setForeground(new java.awt.Color(255, 255, 255));
        SC_Descript_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SC_Descript_JLabel.setText("Description");

        SC_Descript_JTextField.setBackground(new java.awt.Color(240, 240, 240));
        SC_Descript_JTextField.setText("Enter Description");
        SC_Descript_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SC_Descript_JTextFieldActionPerformed(evt);
            }
        });

        SC_Value_JTextField.setBackground(new java.awt.Color(240, 240, 240));
        SC_Value_JTextField.setText("Enter Shortcut");
        SC_Value_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SC_Value_JTextFieldActionPerformed(evt);
            }
        });

        SC_Key_JTextField.setBackground(new java.awt.Color(240, 240, 240));
        SC_Key_JTextField.setText("Enter Hotkey");

        SC_Key_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SC_Key_Label.setForeground(new java.awt.Color(255, 255, 255));
        SC_Key_Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SC_Key_Label.setText("Hotkey");

        SC_Value_JLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SC_Value_JLabel.setForeground(new java.awt.Color(255, 255, 255));
        SC_Value_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SC_Value_JLabel.setText("Shortcut");

        javax.swing.GroupLayout InputTextPanelLayout = new javax.swing.GroupLayout(InputTextPanel);
        InputTextPanel.setLayout(InputTextPanelLayout);
        InputTextPanelLayout.setHorizontalGroup(InputTextPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InputTextPanelLayout.createSequentialGroup().addContainerGap().addGroup(InputTextPanelLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SC_Value_JLabel, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(SC_Descript_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addComponent(SC_Key_Label, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InputTextPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SC_Value_JTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(SC_Key_JTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(SC_Descript_JTextField, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 334,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap()));

        InputTextPanelLayout.setVerticalGroup(InputTextPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputTextPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(InputTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SC_Descript_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SC_Descript_JLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InputTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SC_Value_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SC_Value_JLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InputTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SC_Key_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SC_Key_Label))
                        .addContainerGap()));

        ButtonPanel.setBackground(new java.awt.Color(102, 102, 102));

        Add_button.setBackground(new java.awt.Color(255, 255, 255));
        Add_button.setForeground(new java.awt.Color(102, 102, 102));

        Add_button.setLabel("Add");

        Delete_button.setBackground(new java.awt.Color(255, 255, 255));
        Delete_button.setForeground(new java.awt.Color(102, 102, 102));
        
        Delete_button.setLabel("Delete");

        Edit_button.setBackground(new java.awt.Color(255, 255, 255));
        Edit_button.setForeground(new java.awt.Color(102, 102, 102));
        Edit_button.setLabel("Edit");

        Save_button.setBackground(new java.awt.Color(255, 255, 255));
        Save_button.setForeground(new java.awt.Color(102, 102, 102));
        Save_button.setLabel("Save");

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout
                .setHorizontalGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ButtonPanelLayout.createSequentialGroup().addGap(92, 92, 92)
                                .addComponent(Add_button, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Delete_button, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Edit_button, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Save_button, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        ButtonPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
                new java.awt.Component[] { Add_button, Delete_button, Edit_button, Save_button });

        ButtonPanelLayout.setVerticalGroup(ButtonPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ButtonPanelLayout.createSequentialGroup().addContainerGap()
                        .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Save_button, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Edit_button, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Delete_button, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Add_button, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        ButtonPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL,
                new java.awt.Component[] { Add_button, Delete_button, Edit_button, Save_button });

        javax.swing.GroupLayout Master_MainPannelLayout = new javax.swing.GroupLayout(Master_MainPannel);
        Master_MainPannel.setLayout(Master_MainPannelLayout);
        Master_MainPannelLayout.setHorizontalGroup(Master_MainPannelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Master_MainPannelLayout.createSequentialGroup()
                        .addComponent(Master_SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Master_MainPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DisplayTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Master_LabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(Master_MainPannelLayout.createSequentialGroup().addGap(6, 6, 6).addComponent(
                                        InputTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(ButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap()));

        Master_MainPannelLayout.setVerticalGroup(Master_MainPannelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(Master_MainPannelLayout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(
                        Master_SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Master_MainPannelLayout.createSequentialGroup().addGap(44, 44, 44)
                        .addComponent(Master_LabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DisplayTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(ButtonPanel,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 650, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Master_MainPannel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 550, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Master_MainPannel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt
     */
    private void Layout_LabelMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Layout_LabelMouseEntered
        // TODO add your handling code here:
    }// GEN-LAST:event_Layout_LabelMouseEntered

    /**
     * 
     * @param evt
     */
    private void Shortcut_LabelMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Shortcut_LabelMouseEntered
        // TODO add your handling code here:
    }// GEN-LAST:event_Shortcut_LabelMouseEntered

    /**
     * 
     * @param evt
     */
    private void Share_LabelMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Share_LabelMouseEntered
        // TODO add your handling code here:
    }// GEN-LAST:event_Share_LabelMouseEntered

    /**
     * 
     * @param evt
     */
    private void Groups_LabelMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Groups_LabelMouseEntered
        // TODO add your handling code here:
    }// GEN-LAST:event_Groups_LabelMouseEntered

    /**
     * 
     * @param evt
     */
    private void Statistics_LabelMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Statistics_LabelMouseEntered
        // TODO add your handling code here:
    }// GEN-LAST:event_Statistics_LabelMouseEntered

    /**
     * 
     * @param evt
     */
    private void General_LabelMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_General_LabelMouseEntered
        // TODO add your handling code here:
    }// GEN-LAST:event_General_LabelMouseEntered

    /**
     * 
     * @param evt
     */
    private void Help_LabelMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Help_LabelMouseEntered
        
    }// GEN-LAST:event_Help_LabelMouseEntered

    /**
     * 
     * @param evt
     */
    private void Profile_LabelMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Profile_LabelMouseEntered
        // TODO add your handling code here:
    }// GEN-LAST:event_Profile_LabelMouseEntered

    /**
     * 
     * @param evt
     */
    private void SC_Descript_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SC_Descript_JTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_SC_Descript_JTextFieldActionPerformed

    /**
     * 
     * @param evt
     */
    private void SC_Value_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SC_Value_JTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_SC_Value_JTextFieldActionPerformed

    /**
     * 
     * @param evt
     */
    private void Add_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                           
       // Add_button.addActionListener(e -> {
           // deleteFromSCMAP();
    }

    /**
     * 
     * @param evt
     */
    private void Delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * 
     * @param evt
     */
    private void Edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * 
     * @param evt
     */
    private void Save_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public void ShortcutFrame_init() {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShortcutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShortcutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShortcutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShortcutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShortcutFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Add_button;
    private javax.swing.JPanel ButtonPanel;
    private java.awt.Button Delete_button;
    private javax.swing.JPanel DisplayTextPanel;
    private java.awt.Button Edit_button;
    private javax.swing.JLabel General_Label;
    private javax.swing.JLabel Groups_Label;
    private javax.swing.JLabel Help_Label;
    private javax.swing.JPanel InputTextPanel;
    private javax.swing.JLabel Layout_Label;
    private javax.swing.JLabel Logo_Label;
    private javax.swing.JLabel MasterPanelLabel;
    private javax.swing.JPanel Master_LabelPanel;
    private javax.swing.JPanel Master_MainPannel;
    private javax.swing.JPanel Master_SidePanel;
    private javax.swing.JLabel Profile_Label;
    private javax.swing.JLabel SC_Descript_JLabel;
    private javax.swing.JTextField SC_Descript_JTextField;
    private javax.swing.JTextArea SC_JTextArea;
    private javax.swing.JList<String> SC_Key_JList;
    private javax.swing.JTextField SC_Key_JTextField;
    private javax.swing.JLabel SC_Key_Label;
    private javax.swing.JLabel SC_Value_JLabel;
    private javax.swing.JTextField SC_Value_JTextField;
    private java.awt.Button Save_button;
    private javax.swing.JLabel Share_Label;
    private javax.swing.JLabel Shortcut_Label;
    private javax.swing.JLabel Statistics_Label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
