/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.purplecobras.keyboardwarrior.gui.v2.master;

/**
 *
 * @author JoshPoe
 */
public class MASTER_PANEL extends javax.swing.JPanel {

    /**
     * Creates new form MASTER_RIGHT_PANEL
     */
    public MASTER_PANEL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Master_MainPannel = new javax.swing.JPanel();
        Master_LabelPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        MasterPanelLabel = new javax.swing.JLabel();
        Master_SidePanel = new javax.swing.JPanel();
        Logo_Label = new javax.swing.JLabel();
        Layout_Label = new javax.swing.JLabel();
        Shortcut_Label = new javax.swing.JLabel();
        Share_Label = new javax.swing.JLabel();
        Groups_Label = new javax.swing.JLabel();
        Statistics_Label = new javax.swing.JLabel();
        General_Label = new javax.swing.JLabel();
        Help_Label = new javax.swing.JLabel();
        Profile_Label = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(650, 550));

        Master_MainPannel.setBackground(new java.awt.Color(102, 102, 102));
        Master_MainPannel.setPreferredSize(new java.awt.Dimension(650, 550));

        Master_LabelPanel.setBackground(new java.awt.Color(102, 102, 102));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        MasterPanelLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MasterPanelLabel.setForeground(new java.awt.Color(255, 255, 255));
        MasterPanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MasterPanelLabel.setText("Sample");
        MasterPanelLabel.setToolTipText("");

        javax.swing.GroupLayout Master_LabelPanelLayout = new javax.swing.GroupLayout(Master_LabelPanel);
        Master_LabelPanel.setLayout(Master_LabelPanelLayout);
        Master_LabelPanelLayout.setHorizontalGroup(
            Master_LabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Master_LabelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Master_LabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MasterPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        Master_LabelPanelLayout.setVerticalGroup(
            Master_LabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Master_LabelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MasterPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Master_SidePanel.setBackground(new java.awt.Color(51, 51, 51));
        Master_SidePanel.setPreferredSize(new java.awt.Dimension(200, 550));

        Logo_Label.setBackground(new java.awt.Color(11, 11, 11));
        Logo_Label.setForeground(new java.awt.Color(255, 255, 255));
        Logo_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyboardwarrior/icon/WHITE_W_HELMET.png"))); // NOI18N

        Layout_Label.setBackground(new java.awt.Color(11, 11, 11));
        Layout_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Layout_Label.setForeground(new java.awt.Color(255, 255, 255));
        Layout_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyboardwarrior/icon/006-interface.png"))); // NOI18N
        Layout_Label.setText("Layout");
        Layout_Label.setPreferredSize(new java.awt.Dimension(70, 50));
        Layout_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Layout_LabelMouseEntered(evt);
            }
        });

        Shortcut_Label.setBackground(new java.awt.Color(11, 11, 11));
        Shortcut_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Shortcut_Label.setForeground(new java.awt.Color(255, 255, 255));
        Shortcut_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyboardwarrior/icon/computer_1.png"))); // NOI18N
        Shortcut_Label.setText("Shortcuts");
        Shortcut_Label.setPreferredSize(new java.awt.Dimension(70, 50));
        Shortcut_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Shortcut_LabelMouseEntered(evt);
            }
        });

        Share_Label.setBackground(new java.awt.Color(11, 11, 11));
        Share_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Share_Label.setForeground(new java.awt.Color(255, 255, 255));
        Share_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyboardwarrior/icon/share.png"))); // NOI18N
        Share_Label.setText("Share");
        Share_Label.setPreferredSize(new java.awt.Dimension(70, 50));
        Share_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Share_LabelMouseEntered(evt);
            }
        });

        Groups_Label.setBackground(new java.awt.Color(11, 11, 11));
        Groups_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Groups_Label.setForeground(new java.awt.Color(255, 255, 255));
        Groups_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyboardwarrior/icon/networking.png"))); // NOI18N
        Groups_Label.setText("Groups");
        Groups_Label.setPreferredSize(new java.awt.Dimension(70, 50));
        Groups_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Groups_LabelMouseEntered(evt);
            }
        });

        Statistics_Label.setBackground(new java.awt.Color(11, 11, 11));
        Statistics_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Statistics_Label.setForeground(new java.awt.Color(255, 255, 255));
        Statistics_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyboardwarrior/icon/analytics.png"))); // NOI18N
        Statistics_Label.setText("Statistics");
        Statistics_Label.setPreferredSize(new java.awt.Dimension(70, 50));
        Statistics_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Statistics_LabelMouseEntered(evt);
            }
        });

        General_Label.setBackground(new java.awt.Color(11, 11, 11));
        General_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        General_Label.setForeground(new java.awt.Color(255, 255, 255));
        General_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyboardwarrior/icon/010-configuration.png"))); // NOI18N
        General_Label.setText("General");
        General_Label.setPreferredSize(new java.awt.Dimension(70, 50));
        General_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                General_LabelMouseEntered(evt);
            }
        });

        Help_Label.setBackground(new java.awt.Color(11, 11, 11));
        Help_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Help_Label.setForeground(new java.awt.Color(255, 255, 255));
        Help_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyboardwarrior/icon/communication.png"))); // NOI18N
        Help_Label.setText("Help");
        Help_Label.setPreferredSize(new java.awt.Dimension(70, 50));
        Help_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Help_LabelMouseEntered(evt);
            }
        });

        Profile_Label.setBackground(new java.awt.Color(11, 11, 11));
        Profile_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Profile_Label.setForeground(new java.awt.Color(255, 255, 255));
        Profile_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyboardwarrior/icon/user.png"))); // NOI18N
        Profile_Label.setText("Profile");
        Profile_Label.setPreferredSize(new java.awt.Dimension(70, 50));
        Profile_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Profile_LabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout Master_SidePanelLayout = new javax.swing.GroupLayout(Master_SidePanel);
        Master_SidePanel.setLayout(Master_SidePanelLayout);
        Master_SidePanelLayout.setHorizontalGroup(
            Master_SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Master_SidePanelLayout.createSequentialGroup()
                .addGroup(Master_SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Logo_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Master_SidePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(Master_SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Layout_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Shortcut_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(Master_SidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Master_SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Groups_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Share_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Statistics_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(General_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Help_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Profile_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Master_SidePanelLayout.setVerticalGroup(
            Master_SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Master_SidePanelLayout.createSequentialGroup()
                .addComponent(Logo_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Layout_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Shortcut_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Groups_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Share_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Statistics_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(General_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Help_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(Profile_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Master_MainPannelLayout = new javax.swing.GroupLayout(Master_MainPannel);
        Master_MainPannel.setLayout(Master_MainPannelLayout);
        Master_MainPannelLayout.setHorizontalGroup(
            Master_MainPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Master_MainPannelLayout.createSequentialGroup()
                .addComponent(Master_SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Master_LabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Master_MainPannelLayout.setVerticalGroup(
            Master_MainPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Master_MainPannelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Master_SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Master_MainPannelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Master_LabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Master_MainPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Master_MainPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Layout_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Layout_LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Layout_LabelMouseEntered

    private void Shortcut_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Shortcut_LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Shortcut_LabelMouseEntered

    private void Share_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Share_LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Share_LabelMouseEntered

    private void Groups_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Groups_LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Groups_LabelMouseEntered

    private void Statistics_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Statistics_LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Statistics_LabelMouseEntered

    private void General_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_General_LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_General_LabelMouseEntered

    private void Help_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Help_LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Help_LabelMouseEntered

    private void Profile_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile_LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Profile_LabelMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel General_Label;
    private javax.swing.JLabel Groups_Label;
    private javax.swing.JLabel Help_Label;
    private javax.swing.JLabel Layout_Label;
    private javax.swing.JLabel Logo_Label;
    private javax.swing.JLabel MasterPanelLabel;
    private javax.swing.JPanel Master_LabelPanel;
    private javax.swing.JPanel Master_MainPannel;
    private javax.swing.JPanel Master_SidePanel;
    private javax.swing.JLabel Profile_Label;
    private javax.swing.JLabel Share_Label;
    private javax.swing.JLabel Shortcut_Label;
    private javax.swing.JLabel Statistics_Label;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
